### ISSUE TITLE
User Rights in Planing

### ISSUE THREAD

**Issue by arminstutz** [flightlog/flsserver#93]
Please change User rights in prepair planing (Vorbereitung) for a time period to the "Vereinsadmin"  
No rights for period Planing to normal user "Segelflugleiter".

**Comment by pschuler78** [comment]
Deleting a planning day for a normal user should also not be possible, but only if the user is owner of the record.

**Comment by pschuler78** [comment]
Implemented in Release 1.10.5:
- Club-Admin is able to setup new planningdays (batch task) as well as delete planningdays
- Normal user can create new planningdays and delete his own planningdays
- Normal user can edit all planningdays
